name: run mkarchiso

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - name: cleanup work dir
        run: | 
          if [[ -d work ]]
          then
            echo ${{ secrets.SUDO_PASSWD }} | sudo -S rm -rf work/
          fi
          if [[ -d out ]]
          then
            echo ${{ secrets.SUDO_PASSWD }} | sudo -S rm -rf out/
          fi
          
      - uses: actions/checkout@v3
          
      - name: build the ISO
        run: |
          echo ${{ secrets.SUDO_PASSWD }} | sudo -S ./archiso/mkarchiso -v configs/x13s
